version: '3.7'
services:
  es:
    build:
      context: .
      dockerfile: ./containers/dev-local/elasticsearch/Dockerfile
    volumes:
      - network.host=0.0.0.0
      - es-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    expose:
      - 9300
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.9.3
    environment:
      SERVER_NAME: localhost:5601
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - "5601:5601"
    depends_on:
      - es
volumes:
  es-data:
